services:
  server:
    build: .
    ports: 
      - "8000:8000"
    env_file: .env.docker
    depends_on:
      - redis		
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"