services:
  server:
    build: ./app
    ports: 
      - "8000:8000"
    depends_on:
      - redis		
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"